### ISSUE TITLE
How and where to give my own Costume photograph as input ?

### ISSUE THREAD

**Issue by RageshAntonyHM** [HumanAIGC/Cloth2Tex#3]
I couldn't understand this command 

`python phase1_inference.py --g 1_wy --s 1.2 --d "20231017_wy" --steps_one 501 --steps_two 1001
`

Where is the input image in this ?

**Comment by tomguluson92** [comment]
hi, you can check the inner code snippet for a better understanding, thank you very much.

**Comment by RageshAntonyHM** [comment]
@tomguluson92 

I got some idea

And, does it generate a 3D Mesh such as in OBJ format or just a UV like this 
https://github.com/HumanAIGC/Cloth2Tex/blob/main/experiments/20231017_trousers/0_texture_uv_1000.jpg ?

**Comment by tomguluson92** [comment]
@RageshAntonyHM Cloth2Tex only produces structure-plausible UV texture maps.

**Comment by RageshAntonyHM** [comment]
@RageshAntonyHM okay. Then who did you convert to 3D mesh directly like this in Readme ?
![image](https://github.com/HumanAIGC/Cloth2Tex/assets/141845438/2b6036a4-4604-4ec8-80c2-637e2a7c905f)
