### ISSUE TITLE
could you please release template meshes

### ISSUE THREAD

**Issue by bbbbubble** [HumanAIGC/Cloth2Tex#5]
Hi! Could you please release these template meshes and their UV maps? 
Thank you！

**Comment by tomguluson92** [comment]
please check `https://github.com/HumanAIGC/Cloth2Tex/tree/main/template/reference/2_Polo/mesh`

**Comment by bbbbubble** [comment]
Thank you for your quick reply! 
But I found that "10_dress" and "11_skirt" in your released data are the same. And there seems the "8_category" is missing. 
Is thar right? Thanks!
